/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GoogleGuiceSample;

import com.google.inject.AbstractModule;
import com.google.inject.Guice;
import com.google.inject.Injector;

public class App {
    public static void main(String[] args) {
        sample4();
    }

    private static void sample1(){
        Injector injector = Guice.createInjector(new MyModule());
        Client client = injector.getInstance(Client.class);
        client.execute();
    }
    static public class MyModule extends AbstractModule {
        @Override
        protected void configure() {
            // bind(インタフェース).to(実装クラス)
            bind(Service.class).to(ServiceImpl.class);
        }
    }

    private static void sample2(){
        Injector injector = Guice.createInjector(new AbstractModule() {
            protected void configure() {
                bind(Service.class).to(ServiceImpl.class);
            }
        });
        InjectSample injectSample = injector.getInstance(InjectSample.class);
        injectSample.execute();
    }

    private static void sample3(){
        Injector injector = Guice.createInjector(new AbstractModule() {
            protected void configure() {
                bind(Service.class).to(ServiceImpl.class);
            }
        });
        InjectSample2 injectSample2 = injector.getInstance(InjectSample2.class);
        injectSample2.superExecute();
    }

    private static void sample4(){
        Injector injector = Guice.createInjector(new AbstractModule() {
            protected void configure() {
            }
        });
        Client2 client2 = injector.getInstance(Client2.class);
        client2.execute();
    }
}
